name: KMeans Clustering Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Use the latest version
        with:
          node-version: '20'  # Use the latest stable version of Node.js

      - name: Install Python 3.10
        uses: actions/setup-python@v2  # Optionally switch to v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Start server and frontend in the same terminal
        run: |
          # Start the backend server in the background
          make run &

          # Navigate to the frontend directory and start it
          cd frontend && npm start

          # Wait for both processes to finish
          wait

      - name: Verify the server is running
        run: curl -I http://localhost:5000  # Ensure to use the correct port for your Flask app
