name: KMeans Clustering Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install JavaScript dependencies
      run: npm install

    - name: Run the application
      run: |
        make run &
        sleep 10  # Give the server time to start

    - name: Verify the server is running
      run: curl -I http://localhost:3000
