name: KMeans Clustering Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Run the Python application in background
        run: |
          make run &    # Run the backend in the background
          BACKEND_PID=$!  # Capture the process ID
          echo "Backend started with PID $BACKEND_PID"
          sleep 15      # Wait for the server to start

      - name: Start the frontend with npm
        run: |
          # Run the frontend in a subshell
          (
            cd frontend  # Change to your frontend directory
            npm install           # Install frontend dependencies
            npm start             # Start the frontend
          ) &   # Start in the background
          FRONTEND_PID=$!  # Capture the process ID
          echo "Frontend started with PID $FRONTEND_PID"
          sleep 15         # Wait for the frontend to start

      - name: Verify the server is running
        run: curl -I http://localhost:3000

      - name: Clean up
        run: |
          kill $BACKEND_PID || true  # Kill the backend process
          kill $FRONTEND_PID || true  # Kill the frontend process
